---
kind: pipeline
type: docker
name: Build linux amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: Compile
    image: debian:latest
    commands:
    - whoami
    - apt-get update
    - apt-get install -y g++ make libgl-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libpng-dev libjpeg-dev zlib1g-dev 
    - mkdir -p src/standalone/shared src/standalone/game src/standalone/engine
    - make -C src install
    - tar -czf tesseract_unix_x64.tar.gz tesseract.bat server.bat bin64 config media

  - name: publish
    image: plugins/github-release
    settings:
      api_key: 
        from_secret: token
      files:
        - tesseract_unix_x64.tar.gz
    checksum:
        - md5
        - sha1
        - sha256
        - sha512

trigger:
  event:
  - tag

---
kind: pipeline
type: docker
name: Build linux arm

platform:
  arch: arm
  os: linux

steps:
  - name: Compile
    image: debian:latest
    commands:
    - whoami
    - apt-get update
    - apt-get install -y g++ make libgl-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libpng-dev libjpeg-dev zlib1g-dev 
    - mkdir -p src/standalone/shared src/standalone/game src/standalone/engine
    - make -C src install
    - tar -czf tesseract_arm.tar.gz tesseract_unix bin_unix config media

  - name: publish
    image: plugins/github-release
    settings:
      api_key: 
        from_secret: token
      files:
        - tesseract_arm.tar.gz
    checksum:
        - md5
        - sha1
        - sha256
        - sha512

trigger:
  event:
  - tag
  
---
kind: pipeline
type: docker
name: Cross Build windows amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: Compile
    image: debian:latest
    commands:
    - whoami
    - apt-get update
    - apt-get install -y g++ g++-multilib make libgl-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libpng-dev libjpeg-dev zlib1g-dev mingw-w64 zip
    - mkdir -p src/standalone/shared src/standalone/game src/standalone/engine
    - export PLATFORM=MINGW
    - make -C src install
    - zip -r tesseract_win64.zip tesseract_unix bin_unix config media

  - name: publish
    image: plugins/github-release
    settings:
      api_key: 
        from_secret: token
      files:
        - tesseract_win64.zip
    checksum:
        - md5
        - sha1
        - sha256
        - sha512

trigger:
  event:
  - tag
