---
kind: pipeline
type: docker
name: Build linux amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: test
    image: debian:latest
    commands:
    - sudo apt-get install g++ make libgl-dev libsdl2-dev libsdl2_image-dev libsdl2_mixer-dev libpng-dev libjpeg-dev zlib1g-dev
    - mkdir -p src/standalone/shared src/standalone/game src/standalone/engine
    - make -C src install
    - tar -cf tesseract_unix_x64 tesseract_unix bin_unix config media

  - name: publish
    image: plugins/github-release
    settings:
      api_key: 
        from_secret: token
      files:
        - tesseract_unix_x64
    checksum:
        - md5
        - sha1
        - sha256
        - sha512

trigger:
  event:
  - push
