# Sync the repository once a day

name: Periodically sync the repo

# Controls when the action will run. 
on:
  # once a day
  schedule:
  - cron: "0 6 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Update-Repo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: install git-svn
        run: |
          sudo add-apt-repository ppa:git-core/ppa
          sudo apt-get update
          sudo apt-get install git-svn

      - name: svn update
        run: | 
          git --version
          git svn clone -rHEAD svn://svn.tuxfamily.org/svnroot/tesseract/main tmp
          ls tmp
          mv tmp/* .
          rm -rf tmp
          ls
          
      - name: commit new changes
        run: | 
          git config --local user.name "Corentin-Luc-Artaud"
          git config --local user.email "corentin.luc.artaud@gmail.com"
          git add *
          git commit -m "automated update on $(date -u -R)"
          git branch 
          git push
